### ISSUE TITLE
Captured Named Groups Always return nulls for indexes above 0

### ISSUE THREAD

**Issue by matthew-elisha** [florianingerl/com.florianingerl.util.regex#10]
I tested the following code
`Matcher matcher = Pattern.compile("(?x)" + "(?(DEFINE)" + "(?<sum> (?'summand')(?:\\+(?'summand'))+ )"
                + "(?<summand>  (?'product') | (?'number') )" + "(?<product> (?'factor')(?:\\*(?'factor'))+ )"
                + "(?<factor>(?'number') )" + "(?<number>\\d++)" + ")" + "(?'sum')").matcher("5+6*8");
 matcher.matches();`

But the following line was simply returning NULL:
`System.out.Println(matcher.group("number"));`

Please what am I getting wrong?

**Comment by florianingerl** [comment]
Hello Matthew,
There is no group called number on the lowest level.
Number is only a group nested in another group.
You would have to inspect the capture tree to see what the group number
actually captured!

All the best,
Florian

All

**Comment by matthew-elisha** [comment]
Thanks alot.

**Comment by matthew-elisha** [comment]
Hi,

I still have an issue pls. The captured group value for all groups above index 1 return null. Is that normal? 
How can I access the captured groups by name using the following pattern:

`Matcher matcher = Pattern.compile("(?x)" + "(?(DEFINE)" + "(?<sum> (?'summand')(?:\\+(?'summand'))+ )"
                + "(?<summand>  (?'product') | (?'number') )" + "(?<product> (?'factor')(?:\\*(?'factor'))+ )"
                + "(?<factor>(?'number') )" + "(?<number>\\d++)" + ")" + "(?'sum')").matcher("5+6*8");
 matcher.matches();`

EDIT:
My point is that I want to be able to access the value of a captured subsequence of the recursive pattern above by using something like this:
`matcher.group('name');`

**Comment by matthew-elisha** [comment]
Hello,

Any response to the above please?

**Comment by florianingerl** [comment]
You have to inspect the capture tree to see what these groups captured!

**Comment by Reissner** [comment]
Hello, 
I agree with [matthew-elisha](https://github.com/matthew-elisha) assuming that he invoked `Matcher.find` or that like. 
Whereas groups work for Matchers they don't for MatchResults, which is quite clear 
looking at the implementation of Matcher.toMatchResult(). 

I was happy to see that MatchResult.group(String) promises to get named group matches, 
but the problem is also with numbered groups 

Example: 
```
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import java.util.regex.MatchResult;

// import com.florianingerl.util.regex.Pattern;
// import com.florianingerl.util.regex.Matcher;
// import com.florianingerl.util.regex.MatchResult;

public class test {
  public static void main(String[] args) {
    Pattern pattern = Pattern.compile("a(\\w+)b");
    Matcher matcher = pattern.matcher("ahellob");
    System.out.println("match: " + matcher.find());
    System.out.println("group1: "+matcher.toMatchResult().group(1));
  }
}
```
prints `hello` as expected. 
For the ingerl classes, the result is `null`, because the MatchResult is an unmatched matcher, no find was applied yet. 
It shall be `hello`. 

The same is true for named groups. 

A fix I would accept just  that `Matcher.toMatchResult()` returns `this`. 
It is not really safe because one could access the internals by casting, 
but I consider this criminal. 
You could also copy the relevant pieces of information.

**Comment by florianingerl** [comment]
The latest commit should
fix the problem

https://github.com/florianingerl/com.florianingerl.util.regex/commit/289e8b106d7beae740ff049f238905135e7e5062

**Comment by Reissner** [comment]
You are really fast! 
Ah, not as minimal as I suggested. Better.. 

Hm.. did you publish? which version? 1.1.10?

**Comment by Reissner** [comment]
Just to be sure: does it work for named groups also? 
According testcase maybe a good idea.

**Comment by florianingerl** [comment]
Hello Reissner,
I just managed to deploy a new version where the bug is fixed.
It is version 1.1.11 and can now be downloaded from Maven Central.
This was a lot of work
All the best,
Florian

**Comment by florianingerl** [comment]
New version 1.1.11 can be downloaded from Maven central where the bug is fixed.
